config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :models
  get 'home/index'
  
  resources :executions
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  
  get "more_info", :to => "home#more_info"
  get "faq", :to => "home#faq"
  get "credits", :to => "home#credits"
  
  resources :executions do
      member { post 'notify' }
      collection do
          post 'notify'
          get 'executions_list'
      end
  end

  
  resources :uploaded_files, :path => "files", :controller => :files
  resources :files
  
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  helper_method :current_or_guest_user
  
  def index
    @files = current_or_guest_user.uploaded_files.order("name DESC").page params[:page]
  end

  def new
    @file = UploadedFile.new(name: "New file")
    render :show
  end

  def show
    @file = UploadedFile.find(params[:id])
    authorize! :show, @file
  end

  def create
    if params[:uploaded_file].nil?
        flash[:error] = t(:error_no_file)
    elsif invalid_params?
        flash[:error] = t(:error_wrong_file_format)
    else
        @file = UploadedFile.new(post_params)
        authorize! :create, @file

        @file.user = current_or_guest_user

        if @file.save
            redirect_to executions_path
        else
            render :action => :new
        end
    end
  end

  def update
    @file = UploadedFile.find(params[:id])
    authorize! :update, @file

    @file.update_attributes(put_params)
    render :show
  end

  def destroy
    @file = UploadedFile.find(params[:id])
    authorize! :destroy, @file

    @file.destroy
    redirect_to :action => :index
  end


  private

  def put_params
      params.permit!
      params[:uploaded_file].slice(:name, :description)
  end

  def invalid_params?
     params.permit!
     ["text/plain","application/pdf"].exclude?(params[:uploaded_file][:file].content_type)
 end

  def post_params
      params.permit!
      params[:uploaded_file].slice(:name, :description, :file)
  end
end

app/views/files/_form.html.erb
<div class="row">
  <%= simple_form_for @file, :html => {:multipart => true, :class => ''} do |f| %>

    <%= f.input :name %>
    <%= f.input :description,  :input_html => { rows: 3, class: 'col-xs-4'} %>

    <% if @file.new_record? %>
      <%= f.input :file, :as => :file %>
    <% else %>
      <p>File: <%= link_to @file.file_file_name, @file.file.url %></p>
    <% end %>

    <%= f.button :submit %>
<% end %>
</div>

app/views/files/_list.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Filename</th>
      <th></th>
    </tr>
  </thead>
  <tbody>

  <% @files.each do |file| %>
    <tr>
      <td><%= link_to file.name, file_path(file) %> </td>
      <td><%= file.description %> </td>
      <td><%= file.file_file_name %> </td>
      <td><%= link_to "<i class='glyphicon glyphicon-download'> </i>".html_safe, "#", :class => 'btn ' %> </td>
    </tr>
  <% end %>

  </tbody>
  <th>
  </th>
</table>

app/views/files/index.html.erb
<div class="row"><h1>Uploaded files</h1></div>

<%= render :partial => 'list' %>

<div class="row">
  <%= paginate @files, :theme => 'twitter-bootstrap', :pagination_class => "pagination-small pagination-centered" %>
</div>

<div class="row">
  <%= link_to "Upload a new file", new_file_path, :class => 'btn btn-large'  %>
</div>

<%= content_for :side do %>
  <h2>Help</h2>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
<% end %>

app/views/files/new.html.erb
<h1>Upload your file</h1>

<div class="row">
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
</div>

<%= render :partial => 'form' %>

app/views/files/show.html.erb
<div class="row"><h1><%= @file.name %></h1></div>

<div class="row">
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
</div>

<%= render :partial => 'form' %>
<hr />

<% unless @file.new_record? %>
  <div class="row">
    <p>Tired of this file?</p>
    <%= link_to '<i class="glyphicon glyphicon-trash"> </i>Delete'.html_safe, @file, :method => :delete, :class => 'btn btn-mini btn-danger' %>
  </div>
<% end %>

app/views/files/update.html.erb
<h1>Files#update</h1>
<p>Find me in app/views/files/update.html.erb</p>