config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :models
  get 'home/index'
  
  resources :executions
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  
  get "more_info", :to => "home#more_info"
  get "faq", :to => "home#faq"
  get "credits", :to => "home#credits"
  
  resources :executions do
      member { post 'notify' }
      collection do
          post 'notify'
          get 'executions_list'
      end
  end

  
  resources :uploaded_files, :path => "files", :controller => :files
  resources :files
  
end

app/views/layouts/_flash_messages.html.erb
<% unless flash.nil? %> 
  <% flash.to_hash.delete_if{|type, message| message.empty?}.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_google_analytics.html.erb
<% if Rails.env.production? %>
<script async src="https://www.googletagmanager.com/gtag/js?id=<%= Rails.application.credentials.dig(:google_analytics) %>"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', '<%= Rails.application.credentials.dig(:google_analytics) %>');
  </script>
<% end %>

app/views/layouts/application.html.erb
<%= render :partial => 'shared/header' %>

<div id="page" class="container">
  <%= render partial: "layouts/flash_messages", flash: flash %>	
  <div class="row">

    <div class="col-xs-12">
      <%= yield %>
    </div>

  </div>
</div>

<%= render :partial => 'shared/footer' %>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contawords</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<% if params[:action] == "edit" %>
  <%= render :partial => 'layouts/navigation' %>
<% end %>

<div id="page" class="container">
  <%= render partial: "layouts/flash_messages", flash: flash %>
  <div class="row">
      <%= yield %>
  </div>
</div>

</body>
</html>

app/views/layouts/home.html.erb
<% content_for :header_menu do %>

  <%= link_to t(:empieza_usarlo), executions_path, :class => "btn btn-large btn-warning", :id => "engage-btn"  %>
  
<% end %>

<%= render :partial => 'shared/header' %>

<div class="container main">
  <%= yield %>
</div>


<%= render :partial => 'shared/footer' %>

</body>
</html>